import React, { useState, useEffect } from 'react';
import toast from 'react-hot-toast';
import api from '../../services/api';
import {
  LayoutDashboard, Bell, BellRing, BellOff, Settings, Users,
  Plus, Search, RefreshCw, ChevronDown, ChevronUp, CheckCircle2,
  X, Check, Zap, AlertTriangle, ShieldAlert, Clock,
  MessageSquare, IndianRupee, Heart, Stethoscope, Shield,
  CalendarDays, Eye, Smartphone, Mail, Phone,
  TrendingUp, Activity, Info, Ban, ScanLine, RadioTower,
  UserCheck, ToggleLeft, ToggleRight, Siren, Flame
} from 'lucide-react';

// ─── TYPES ────────────────────────────────────────────────────────────────────

type TabId = 'dashboard' | 'alerts' | 'rules' | 'subscribers';

interface Alert {
  id: number; alert_code: string; alert_type: string;
  title: string; message: string;
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  status: 'Active' | 'Read' | 'Resolved' | 'Dismissed';
  target_type: string; target_name?: string; related_module?: string;
  sent_in_app: boolean; sent_sms: boolean; sent_email: boolean; sent_whatsapp: boolean;
  is_read: boolean; read_at?: string; resolved_by?: string; resolved_at?: string;
  resolution_note?: string; auto_generated: boolean; created_by?: string;
  created_at?: string; time_ago?: string;
}

interface AlertRule {
  id: number; rule_name: string; alert_type: string; description?: string;
  priority: string; target_type: string;
  trigger_after_days?: number; trigger_threshold?: number; trigger_frequency: string;
  notify_in_app: boolean; notify_sms: boolean; notify_email: boolean; notify_whatsapp: boolean;
  is_active: boolean; last_triggered_at?: string;
}

interface Subscriber {
  id: number; name: string; type: string; phone?: string; email?: string; whatsapp?: string;
  subscribed_types: string[];
  notify_in_app: boolean; notify_sms: boolean; notify_email: boolean; notify_whatsapp: boolean;
  is_active: boolean;
}

interface DashStats {
  total: number; active: number; critical: number; unread: number;
  resolved: number; autoGenerated: number; activeRules: number; subscribers: number;
}

// ─── CONFIG ───────────────────────────────────────────────────────────────────

const priorityConfig = {
  Critical: { color: 'text-rose-700',   bg: 'bg-rose-50',    border: 'border-rose-300',   dot: 'bg-rose-600',   glow: 'shadow-rose-100',   badge: 'bg-rose-600 text-white', icon: Flame },
  High:     { color: 'text-orange-700', bg: 'bg-orange-50',  border: 'border-orange-200', dot: 'bg-orange-500', glow: 'shadow-orange-100', badge: 'bg-orange-500 text-white', icon: ShieldAlert },
  Medium:   { color: 'text-amber-700',  bg: 'bg-amber-50',   border: 'border-amber-200',  dot: 'bg-amber-500',  glow: 'shadow-amber-100',  badge: 'bg-amber-100 text-amber-800', icon: AlertTriangle },
  Low:      { color: 'text-slate-500',  bg: 'bg-slate-50',   border: 'border-slate-200',  dot: 'bg-slate-400',  glow: '',                   badge: 'bg-slate-100 text-slate-700', icon: Info },
};

const statusConfig = {
  Active:    { color: 'text-rose-700',    bg: 'bg-rose-50',    border: 'border-rose-200',    dot: 'bg-rose-500 animate-pulse' },
  Read:      { color: 'text-slate-600',   bg: 'bg-slate-50',   border: 'border-slate-200',   dot: 'bg-slate-400' },
  Resolved:  { color: 'text-emerald-700', bg: 'bg-emerald-50', border: 'border-emerald-200', dot: 'bg-emerald-500' },
  Dismissed: { color: 'text-slate-400',   bg: 'bg-slate-50',   border: 'border-slate-100',   dot: 'bg-slate-300' },
};

const alertTypeConfig: Record<string, { icon: React.ElementType; color: string; bg: string }> = {
  'Fee Overdue':          { icon: IndianRupee,  color: 'text-rose-600',   bg: 'bg-rose-50' },
  'Outpass Overdue':      { icon: Clock,        color: 'text-orange-600', bg: 'bg-orange-50' },
  'Medicine Low Stock':   { icon: Stethoscope,  color: 'text-violet-600', bg: 'bg-violet-50' },
  'Medicine Expiry':      { icon: Stethoscope,  color: 'text-amber-600',  bg: 'bg-amber-50' },
  'Complaint Unresolved': { icon: MessageSquare,color: 'text-blue-600',   bg: 'bg-blue-50' },
  'Health Follow-Up':     { icon: Heart,        color: 'text-pink-600',   bg: 'bg-pink-50' },
  'Student Birthday':     { icon: CalendarDays, color: 'text-teal-600',   bg: 'bg-teal-50' },
  'Visitor Overstay':     { icon: Eye,          color: 'text-indigo-600', bg: 'bg-indigo-50' },
  'Leave Abuse':          { icon: CalendarDays, color: 'text-orange-600', bg: 'bg-orange-50' },
  'Rule Violation':       { icon: Shield,       color: 'text-rose-600',   bg: 'bg-rose-50' },
  'Staff Absent':         { icon: Users,        color: 'text-slate-600',  bg: 'bg-slate-50' },
  'Curfew Breach':        { icon: Siren,        color: 'text-rose-700',   bg: 'bg-rose-100' },
  'Custom':               { icon: Bell,         color: 'text-slate-600',  bg: 'bg-slate-50' },
  'System':               { icon: Settings,     color: 'text-slate-600',  bg: 'bg-slate-50' },
};

const ALL_ALERT_TYPES = Object.keys(alertTypeConfig);

// ─── MINI COMPONENTS ──────────────────────────────────────────────────────────

const PriorityBadge: React.FC<{ priority: string }> = ({ priority }) => {
  const c = priorityConfig[priority as keyof typeof priorityConfig] ?? priorityConfig.Low;
  return (
    <span className={`inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded-full text-[8px] font-bold ${c.badge}`}>
      <span className={`w-1.5 h-1.5 rounded-full ${c.dot}`} />{priority}
    </span>
  );
};

const StatusBadge: React.FC<{ status: string }> = ({ status }) => {
  const c = statusConfig[status as keyof typeof statusConfig] ?? statusConfig.Active;
  return (
    <span className={`inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded-full text-[8px] font-bold border ${c.color} ${c.bg} ${c.border}`}>
      <span className={`w-1.5 h-1.5 rounded-full ${c.dot}`} />{status}
    </span>
  );
};

const ChannelIcons: React.FC<{ alert: Alert }> = ({ alert }) => (
  <div className="flex items-center gap-0.5">
    {alert.sent_in_app  && <span title="In-App"><Bell className="w-2.5 h-2.5 text-indigo-400" /></span>}
    {alert.sent_sms     && <span title="SMS"><Smartphone className="w-2.5 h-2.5 text-teal-400" /></span>}
    {alert.sent_email   && <span title="Email"><Mail className="w-2.5 h-2.5 text-amber-400" /></span>}
    {alert.sent_whatsapp && <span title="WhatsApp"><MessageSquare className="w-2.5 h-2.5 text-emerald-400" /></span>}
  </div>
);

// ─── DASHBOARD TAB ────────────────────────────────────────────────────────────

interface DashboardTabProps {
  stats: DashStats; byType: Record<string, number>; byPriority: Record<string, number>;
  byTarget: Record<string, number>; channelStats: any; criticalAlerts: Alert[];
  recentAlerts: Alert[]; trend: any[]; loading: boolean;
  onTabChange: (t: TabId) => void; onMarkRead: (id: number) => void; onResolve: (id: number) => void;
}

const DashboardTab: React.FC<DashboardTabProps> = ({
  stats, byType, byPriority, byTarget, channelStats, criticalAlerts, recentAlerts, trend, loading, onTabChange, onMarkRead, onResolve
}) => (
  <div className="space-y-2">
    {/* Stats Row */}
    <div className="grid grid-cols-4 gap-1.5">
      {[
        { label: 'Total Alerts',    value: stats.total,          color: 'text-slate-700',   bg: 'bg-slate-100',  border: 'border-slate-200' },
        { label: 'Active',          value: stats.active,         color: 'text-rose-700',    bg: 'bg-rose-50',    border: 'border-rose-200' },
        { label: 'Critical',        value: stats.critical,       color: 'text-rose-800',    bg: 'bg-rose-100',   border: 'border-rose-300' },
        { label: 'Unread',          value: stats.unread,         color: 'text-amber-700',   bg: 'bg-amber-50',   border: 'border-amber-200' },
        { label: 'Resolved',        value: stats.resolved,       color: 'text-emerald-700', bg: 'bg-emerald-50', border: 'border-emerald-200' },
        { label: 'Auto-Generated',  value: stats.autoGenerated,  color: 'text-indigo-700',  bg: 'bg-indigo-50',  border: 'border-indigo-200' },
        { label: 'Active Rules',    value: stats.activeRules,    color: 'text-violet-700',  bg: 'bg-violet-50',  border: 'border-violet-200' },
        { label: 'Subscribers',     value: stats.subscribers,    color: 'text-teal-700',    bg: 'bg-teal-50',    border: 'border-teal-200' },
      ].map(s => (
        <div key={s.label} className={`${s.bg} border ${s.border} rounded-xl p-1.5 text-center`}>
          <p className={`text-lg font-black ${s.color} leading-none`}>{s.value}</p>
          <p className={`text-[7px] font-bold ${s.color} uppercase tracking-wide mt-0.5 leading-tight`}>{s.label}</p>
        </div>
      ))}
    </div>

    {/* Critical Alerts Banner */}
    {stats.critical > 0 && (
      <div className="bg-rose-50 border border-rose-300 rounded-xl p-2 flex items-center gap-2 shadow-sm shadow-rose-100">
        <Siren className="w-4 h-4 text-rose-600 animate-pulse flex-shrink-0" />
        <p className="text-[9px] font-bold text-rose-800 flex-1">{stats.critical} critical alert{stats.critical > 1 ? 's' : ''} require immediate attention!</p>
        <button onClick={() => onTabChange('alerts')} className="text-[8px] font-bold text-rose-600 hover:text-rose-800 cursor-pointer transition">View All →</button>
      </div>
    )}

    <div className="grid grid-cols-2 gap-2">
      {/* Priority Breakdown */}
      <div className="bg-white border border-slate-200 rounded-xl p-2.5 shadow-xs">
        <h3 className="text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-2 flex items-center gap-1"><ShieldAlert className="w-2.5 h-2.5" /> By Priority</h3>
        <div className="space-y-1.5">
          {(['Critical', 'High', 'Medium', 'Low'] as const).map(p => {
            const pc = priorityConfig[p];
            const count = byPriority[p] || 0;
            const maxPri = Math.max(...Object.values(byPriority), 1);
            return (
              <div key={p} className="flex items-center gap-1.5">
                <span className={`w-1.5 h-1.5 rounded-full ${pc.dot} flex-shrink-0`} />
                <span className={`text-[8px] font-bold ${pc.color} w-12`}>{p}</span>
                <div className="flex-1 h-1 bg-slate-100 rounded-full overflow-hidden">
                  <div className={`h-full rounded-full ${pc.dot.replace('animate-pulse','')}`} style={{ width: `${(count / maxPri) * 100}%` }} />
                </div>
                <span className={`text-[9px] font-black w-4 text-right ${pc.color}`}>{count}</span>
              </div>
            );
          })}
        </div>
      </div>

      {/* By Target */}
      <div className="bg-white border border-slate-200 rounded-xl p-2.5 shadow-xs">
        <h3 className="text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-2 flex items-center gap-1"><Users className="w-2.5 h-2.5" /> By Target</h3>
        <div className="space-y-1.5">
          {Object.entries(byTarget).map(([target, count]) => {
            const maxT = Math.max(...Object.values(byTarget), 1);
            return (
              <div key={target} className="flex items-center gap-1.5">
                <span className="text-[8px] font-bold text-slate-600 w-12 truncate">{target}</span>
                <div className="flex-1 h-1 bg-slate-100 rounded-full overflow-hidden">
                  <div className="h-full bg-indigo-400 rounded-full" style={{ width: `${(count / maxT) * 100}%` }} />
                </div>
                <span className="text-[9px] font-black text-slate-700 w-4 text-right">{count}</span>
              </div>
            );
          })}
        </div>
      </div>

      {/* Type Breakdown */}
      <div className="bg-white border border-slate-200 rounded-xl p-2.5 shadow-xs col-span-2">
        <h3 className="text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-2 flex items-center gap-1"><Activity className="w-2.5 h-2.5" /> Active Alerts by Type</h3>
        <div className="grid grid-cols-4 gap-1">
          {Object.entries(byType).map(([type, count]) => {
            const tc = alertTypeConfig[type] ?? alertTypeConfig.Custom;
            const Icon = tc.icon;
            return (
              <div key={type} className={`${tc.bg} rounded-lg p-1.5 text-center border border-slate-100`}>
                <Icon className={`w-3 h-3 ${tc.color} mx-auto mb-0.5`} />
                <p className="text-[9px] font-black text-slate-900">{count}</p>
                <p className={`text-[6px] font-bold ${tc.color} leading-tight`}>{type}</p>
              </div>
            );
          })}
        </div>
      </div>
    </div>

    {/* Channel Stats */}
    <div className="bg-white border border-slate-200 rounded-xl p-2.5 shadow-xs">
      <h3 className="text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-2 flex items-center gap-1"><RadioTower className="w-2.5 h-2.5" /> Notification Channels Sent</h3>
      <div className="flex gap-3">
        {[
          { label: 'In-App', value: stats.total, icon: Bell, color: 'text-indigo-600', bg: 'bg-indigo-50' },
          { label: 'SMS', value: channelStats?.smsSent ?? 0, icon: Smartphone, color: 'text-teal-600', bg: 'bg-teal-50' },
          { label: 'Email', value: channelStats?.emailSent ?? 0, icon: Mail, color: 'text-amber-600', bg: 'bg-amber-50' },
          { label: 'WhatsApp', value: channelStats?.whatsappSent ?? 0, icon: MessageSquare, color: 'text-emerald-600', bg: 'bg-emerald-50' },
        ].map(ch => {
          const Icon = ch.icon;
          return (
            <div key={ch.label} className={`flex-1 ${ch.bg} rounded-xl p-1.5 text-center border border-slate-100`}>
              <Icon className={`w-4 h-4 ${ch.color} mx-auto mb-0.5`} />
              <p className={`text-[14px] font-black ${ch.color}`}>{ch.value}</p>
              <p className={`text-[8px] font-bold ${ch.color}`}>{ch.label}</p>
            </div>
          );
        })}
      </div>
    </div>

    {/* Critical Alerts List */}
    {criticalAlerts.length > 0 && (
      <div className="bg-white border border-rose-200 rounded-xl p-2.5 shadow-xs">
        <h3 className="text-[9px] font-bold text-rose-700 uppercase tracking-wider mb-2 flex items-center justify-between">
          <span className="flex items-center gap-1"><Siren className="w-2.5 h-2.5 animate-pulse" /> Critical Alerts — Immediate Action Needed</span>
          <button onClick={() => onTabChange('alerts')} className="text-indigo-500 hover:text-indigo-700 font-bold cursor-pointer text-[8px] transition">See all →</button>
        </h3>
        <div className="space-y-1">
          {criticalAlerts.map(a => {
            const tc = alertTypeConfig[a.alert_type] ?? alertTypeConfig.Custom;
            const Icon = tc.icon;
            return (
              <div key={a.id} className="border border-rose-200 bg-rose-50 rounded-lg px-2 py-1.5 flex items-start gap-1.5">
                <Icon className={`w-3 h-3 ${tc.color} flex-shrink-0 mt-0.5`} />
                <div className="flex-1 min-w-0">
                  <p className="text-[9px] font-bold text-slate-900 truncate">{a.title}</p>
                  <p className="text-[8px] text-slate-500 font-semibold mt-0.5">{a.target_type}{a.target_name ? ` · ${a.target_name}` : ''} · {a.time_ago}</p>
                </div>
                <div className="flex items-center gap-0.5 flex-shrink-0">
                  <button onClick={() => onMarkRead(a.id)} className="p-0.5 hover:bg-rose-100 rounded cursor-pointer transition" title="Mark Read">
                    <Check className="w-2.5 h-2.5 text-rose-500" />
                  </button>
                  <button onClick={() => onResolve(a.id)} className="p-0.5 hover:bg-emerald-100 rounded cursor-pointer transition" title="Resolve">
                    <CheckCircle2 className="w-2.5 h-2.5 text-emerald-500" />
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    )}
  </div>
);

// ─── ALERTS TAB ───────────────────────────────────────────────────────────────

interface AlertsTabProps {
  alerts: Alert[]; loading: boolean;
  onRefresh: () => void; onRunScan: () => void; scanning: boolean;
}

const AlertsTab: React.FC<AlertsTabProps> = ({ alerts, loading, onRefresh, onRunScan, scanning }) => {
  const [search, setSearch]           = useState('');
  const [filterStatus, setFS]         = useState('Active');
  const [filterPriority, setFP]       = useState('all');
  const [filterType, setFT]           = useState('all');
  const [expandedId, setExpanded]     = useState<number | null>(null);
  const [showCreateForm, setSCF]      = useState(false);
  const [resolveModal, setResolveModal] = useState<Alert | null>(null);
  const [resolveNote, setRN]          = useState('');
  const [resolveBy, setRB]            = useState('Warden');
  const [submitting, setSub]          = useState(false);
  const [actioningId, setActioningId] = useState<number | null>(null);

  const [form, setForm] = useState({
    alert_type: 'Custom', title: '', message: '', priority: 'Medium',
    target_type: 'Admin', target_name: '', related_module: '',
    sent_sms: false, sent_email: false, sent_whatsapp: false, created_by: 'Admin',
  });

  const filtered = alerts.filter(a => {
    const matchS = !search || [a.title, a.message, a.alert_code, a.target_name]
      .some(f => f?.toLowerCase().includes(search.toLowerCase()));
    const matchSt = filterStatus === 'all' || a.status === filterStatus;
    const matchPri = filterPriority === 'all' || a.priority === filterPriority;
    const matchT = filterType === 'all' || a.alert_type === filterType;
    return matchS && matchSt && matchPri && matchT;
  });

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.title.trim() || !form.message.trim()) { toast.error('Title and message required'); return; }
    setSub(true);
    try {
      const res = await api.post('/school/hostel/alerts/create', form);
      if (res.data.success) { toast.success(res.data.message); setSCF(false); onRefresh(); }
    } catch (err: any) { toast.error(err.response?.data?.message || 'Failed'); }
    finally { setSub(false); }
  };

  const handleMarkRead = async (id: number) => {
    setActioningId(id);
    try { const r = await api.post(`/school/hostel/alerts/${id}/read`); if (r.data.success) { toast.success('Marked as read'); onRefresh(); } } catch { toast.error('Failed'); }
    finally { setActioningId(null); }
  };

  const handleDismiss = async (id: number) => {
    setActioningId(id);
    try { const r = await api.post(`/school/hostel/alerts/${id}/dismiss`); if (r.data.success) { toast.success('Alert dismissed'); onRefresh(); } } catch { toast.error('Failed'); }
    finally { setActioningId(null); }
  };

  const handleResolve = async () => {
    if (!resolveModal) return;
    setSub(true);
    try {
      const r = await api.post(`/school/hostel/alerts/${resolveModal.id}/resolve`, { resolved_by: resolveBy, resolution_note: resolveNote });
      if (r.data.success) { toast.success('Alert resolved!'); setResolveModal(null); setRN(''); onRefresh(); }
    } catch { toast.error('Failed'); }
    finally { setSub(false); }
  };

  const inp = 'w-full border border-slate-300 rounded-lg px-2 py-1 text-[10px] font-semibold outline-none focus:ring-1 focus:ring-indigo-500';
  const lbl = 'block text-[8px] font-bold text-slate-500 uppercase tracking-wide mb-0.5';

  return (
    <div className="space-y-2">
      {/* Toolbar */}
      <div className="flex flex-wrap gap-1.5 items-center">
        <div className="relative flex-1 min-w-28">
          <Search className="absolute left-2 top-1.5 w-3 h-3 text-slate-400" />
          <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search alerts..."
            className="w-full pl-6 pr-2 py-1 text-[10px] font-semibold border border-slate-300 rounded-lg outline-none focus:ring-1 focus:ring-indigo-500" />
        </div>
        <select value={filterStatus} onChange={e => setFS(e.target.value)} className="border border-slate-300 rounded-lg px-2 py-1 text-[9px] font-semibold bg-white cursor-pointer outline-none">
          {['all', 'Active', 'Read', 'Resolved', 'Dismissed'].map(s => <option key={s} value={s}>{s === 'all' ? 'All Status' : s}</option>)}
        </select>
        <select value={filterPriority} onChange={e => setFP(e.target.value)} className="border border-slate-300 rounded-lg px-2 py-1 text-[9px] font-semibold bg-white cursor-pointer outline-none">
          {['all', 'Critical', 'High', 'Medium', 'Low'].map(p => <option key={p} value={p}>{p === 'all' ? 'All Priority' : p}</option>)}
        </select>
        <select value={filterType} onChange={e => setFT(e.target.value)} className="border border-slate-300 rounded-lg px-2 py-1 text-[9px] font-semibold bg-white cursor-pointer outline-none max-w-[120px]">
          <option value="all">All Types</option>
          {ALL_ALERT_TYPES.map(t => <option key={t}>{t}</option>)}
        </select>
        <button onClick={onRunScan} disabled={scanning}
          className="flex items-center gap-1 px-2 py-1 bg-violet-600 text-white font-bold text-[9px] rounded-lg cursor-pointer hover:bg-violet-700 transition disabled:opacity-70">
          <ScanLine className={`w-3 h-3 ${scanning ? 'animate-spin' : ''}`} /> {scanning ? 'Scanning...' : 'Auto Scan'}
        </button>
        <button onClick={() => setSCF(!showCreateForm)}
          className="flex items-center gap-1 px-2 py-1 bg-indigo-600 text-white font-bold text-[9px] rounded-lg cursor-pointer hover:bg-indigo-700 transition">
          <Plus className="w-3 h-3" /> Create Alert
        </button>
      </div>

      {/* Create Form */}
      {showCreateForm && (
        <div className="bg-white border border-indigo-200 rounded-xl p-2.5 shadow-xs">
          <h3 className="text-[10px] font-bold text-slate-800 flex items-center gap-1.5 mb-2 pb-1 border-b border-slate-100">
            <Plus className="w-3 h-3 text-indigo-500" /> Create Custom Alert
          </h3>
          <form onSubmit={handleCreate} className="space-y-1.5">
            <div className="grid grid-cols-2 gap-1.5">
              <div>
                <label className={lbl}>Alert Type</label>
                <select value={form.alert_type} onChange={e => setForm(f => ({ ...f, alert_type: e.target.value }))} className={inp}>
                  {ALL_ALERT_TYPES.map(t => <option key={t}>{t}</option>)}
                </select>
              </div>
              <div>
                <label className={lbl}>Priority</label>
                <select value={form.priority} onChange={e => setForm(f => ({ ...f, priority: e.target.value }))} className={inp}>
                  {['Critical', 'High', 'Medium', 'Low'].map(p => <option key={p}>{p}</option>)}
                </select>
              </div>
              <div>
                <label className={lbl}>Target Audience</label>
                <select value={form.target_type} onChange={e => setForm(f => ({ ...f, target_type: e.target.value }))} className={inp}>
                  {['Admin', 'Warden', 'Student', 'Parent', 'All'].map(t => <option key={t}>{t}</option>)}
                </select>
              </div>
              <div>
                <label className={lbl}>Target Person (optional)</label>
                <input value={form.target_name} onChange={e => setForm(f => ({ ...f, target_name: e.target.value }))} placeholder="Student name if specific" className={inp} />
              </div>
              <div className="col-span-2">
                <label className={lbl}>Alert Title *</label>
                <input value={form.title} onChange={e => setForm(f => ({ ...f, title: e.target.value }))} className={inp} required />
              </div>
              <div className="col-span-2">
                <label className={lbl}>Alert Message *</label>
                <textarea rows={3} value={form.message} onChange={e => setForm(f => ({ ...f, message: e.target.value }))} className={`${inp} resize-none`} required />
              </div>
              <div className="col-span-2 flex items-center gap-4">
                <p className="text-[8px] font-bold text-slate-500 uppercase">Send via:</p>
                {[
                  { key: 'sent_sms', label: 'SMS', icon: Smartphone },
                  { key: 'sent_email', label: 'Email', icon: Mail },
                  { key: 'sent_whatsapp', label: 'WhatsApp', icon: MessageSquare },
                ].map(ch => {
                  const Icon = ch.icon;
                  return (
                    <label key={ch.key} className="flex items-center gap-1 cursor-pointer">
                      <input type="checkbox" checked={(form as any)[ch.key]} onChange={e => setForm(f => ({ ...f, [ch.key]: e.target.checked }))} className="w-3 h-3" />
                      <Icon className="w-2.5 h-2.5 text-slate-500" />
                      <span className="text-[9px] font-bold text-slate-600">{ch.label}</span>
                    </label>
                  );
                })}
              </div>
            </div>
            <div className="flex gap-1.5 pt-1">
              <button type="submit" disabled={submitting}
                className="flex-1 flex items-center justify-center gap-1 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-[10px] rounded-xl transition disabled:opacity-60">
                <Zap className="w-3 h-3" /> {submitting ? 'Creating...' : 'Create Alert'}
              </button>
              <button type="button" onClick={() => setSCF(false)} className="px-3 py-1.5 border border-slate-300 text-slate-600 font-bold text-[10px] rounded-xl hover:bg-slate-50 transition">Cancel</button>
            </div>
          </form>
        </div>
      )}

      {/* Alert Count */}
      <div className="flex items-center justify-between">
        <p className="text-[8px] font-bold text-slate-400">{filtered.length} alert{filtered.length !== 1 ? 's' : ''}</p>
        {filtered.some(a => a.status === 'Active' && !a.is_read) && (
          <button onClick={async () => { try { const r = await api.post('/school/hostel/alerts/mark-all-read'); if (r.data.success) { toast.success(r.data.message); onRefresh(); } } catch { toast.error('Failed'); } }}
            className="text-[8px] font-bold text-indigo-500 hover:text-indigo-700 cursor-pointer transition">Mark all read</button>
        )}
      </div>

      {/* Alerts */}
      {loading ? (
        <div className="text-center py-8 text-[10px] text-slate-400 font-semibold">Loading alerts...</div>
      ) : filtered.length === 0 ? (
        <div className="text-center py-8 flex flex-col items-center gap-2">
          <BellOff className="w-10 h-10 text-slate-200" />
          <p className="text-[10px] text-slate-400 font-semibold">No alerts found</p>
        </div>
      ) : (
        <div className="space-y-1">
          {filtered.map(a => {
            const pc = priorityConfig[a.priority] ?? priorityConfig.Low;
            const sc = statusConfig[a.status] ?? statusConfig.Active;
            const tc = alertTypeConfig[a.alert_type] ?? alertTypeConfig.Custom;
            const TypeIcon = tc.icon;
            const PriorityIcon = pc.icon;
            const isCritical = a.priority === 'Critical' && a.status === 'Active';
            return (
              <div key={a.id} className={`bg-white border rounded-xl shadow-xs transition ${isCritical ? `${pc.border} ${pc.glow} shadow-sm` : a.status === 'Active' ? 'border-slate-200 hover:border-indigo-200' : 'border-slate-100 opacity-70'}`}>
                <div className="px-2.5 py-2 flex items-start gap-2">
                  {/* Type Icon */}
                  <div className={`p-1 rounded-lg flex-shrink-0 ${tc.bg} mt-0.5`}>
                    <TypeIcon className={`w-3 h-3 ${tc.color}`} />
                  </div>

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-1.5 flex-wrap">
                      {!a.is_read && <span className="w-1.5 h-1.5 rounded-full bg-indigo-500 flex-shrink-0 animate-pulse" />}
                      <span className="text-[8px] font-bold text-slate-400">{a.alert_code}</span>
                      <h4 className={`text-[10px] font-bold text-slate-900 flex-1 min-w-0 truncate ${isCritical ? 'text-rose-900' : ''}`}>{a.title}</h4>
                    </div>
                    <div className="flex items-center gap-1.5 mt-0.5 flex-wrap">
                      <PriorityBadge priority={a.priority} />
                      <StatusBadge status={a.status} />
                      <span className="text-[8px] text-slate-400 font-semibold">{a.alert_type}</span>
                      <span className="text-[8px] text-slate-400 font-semibold">→ {a.target_type}{a.target_name ? `: ${a.target_name}` : ''}</span>
                      {a.auto_generated && <span className="text-[7px] font-bold bg-violet-50 text-violet-600 border border-violet-100 px-1 rounded">Auto</span>}
                    </div>
                    <div className="flex items-center gap-2 mt-0.5">
                      <ChannelIcons alert={a} />
                      <span className="text-[7px] text-slate-400">{a.time_ago}</span>
                    </div>

                    {expandedId === a.id && (
                      <div className="mt-1.5 border-t border-slate-100 pt-1.5 space-y-1">
                        <p className="text-[9px] text-slate-700 font-semibold leading-relaxed whitespace-pre-line">{a.message}</p>
                        {a.resolved_by && (
                          <div className="bg-emerald-50 border border-emerald-100 rounded-lg px-2 py-1">
                            <p className="text-[8px] font-bold text-emerald-700">Resolved by {a.resolved_by} on {a.resolved_at}</p>
                            {a.resolution_note && <p className="text-[8px] text-emerald-600 mt-0.5">{a.resolution_note}</p>}
                          </div>
                        )}
                      </div>
                    )}
                  </div>

                  {/* Actions */}
                  <div className="flex flex-col items-end gap-0.5 flex-shrink-0">
                    <div className="flex items-center gap-0.5">
                      {a.status === 'Active' && (
                        <>
                          <button onClick={() => handleMarkRead(a.id)} disabled={actioningId === a.id}
                            className="p-0.5 hover:bg-blue-50 rounded transition cursor-pointer" title="Mark Read">
                            <Eye className="w-2.5 h-2.5 text-blue-500" />
                          </button>
                          <button onClick={() => setResolveModal(a)}
                            className="p-0.5 hover:bg-emerald-50 rounded transition cursor-pointer" title="Resolve">
                            <CheckCircle2 className="w-2.5 h-2.5 text-emerald-500" />
                          </button>
                          <button onClick={() => handleDismiss(a.id)} disabled={actioningId === a.id}
                            className="p-0.5 hover:bg-slate-100 rounded transition cursor-pointer" title="Dismiss">
                            <BellOff className="w-2.5 h-2.5 text-slate-400" />
                          </button>
                        </>
                      )}
                      <button onClick={() => setExpanded(expandedId === a.id ? null : a.id)}
                        className="p-0.5 hover:bg-slate-100 rounded transition cursor-pointer">
                        {expandedId === a.id ? <ChevronUp className="w-3 h-3 text-slate-400" /> : <ChevronDown className="w-3 h-3 text-slate-400" />}
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Resolve Modal */}
      {resolveModal && (
        <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-2" onClick={e => e.target === e.currentTarget && setResolveModal(null)}>
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-sm p-3">
            <h3 className="text-[11px] font-bold text-slate-900 flex items-center gap-1.5 mb-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-500" /> Resolve Alert
            </h3>
            <p className="text-[9px] text-slate-500 font-semibold mb-2 truncate">{resolveModal.title}</p>
            <div className="space-y-1.5">
              <div>
                <label className={lbl}>Resolved By</label>
                <input value={resolveBy} onChange={e => setRB(e.target.value)} className={inp} />
              </div>
              <div>
                <label className={lbl}>Resolution Note (optional)</label>
                <textarea rows={3} value={resolveNote} onChange={e => setRN(e.target.value)} placeholder="What action was taken?" className={`${inp} resize-none`} />
              </div>
            </div>
            <div className="flex gap-1.5 mt-2">
              <button onClick={handleResolve} disabled={submitting}
                className="flex-1 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-[10px] rounded-xl transition disabled:opacity-60 cursor-pointer">
                {submitting ? 'Resolving...' : 'Mark Resolved'}
              </button>
              <button onClick={() => setResolveModal(null)} className="px-3 py-1.5 border border-slate-300 text-slate-600 font-bold text-[10px] rounded-xl hover:bg-slate-50 transition cursor-pointer">Cancel</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

// ─── RULES TAB ────────────────────────────────────────────────────────────────

interface RulesTabProps { rules: AlertRule[]; loading: boolean; onRefresh: () => void; }

const RulesTab: React.FC<RulesTabProps> = ({ rules, loading, onRefresh }) => {
  const [showForm, setShowForm]     = useState(false);
  const [toggling, setToggling]     = useState<number | null>(null);
  const [submitting, setSub]        = useState(false);

  const [form, setForm] = useState({
    rule_name: '', alert_type: 'Fee Overdue', description: '',
    priority: 'High', target_type: 'Admin',
    trigger_after_days: '', trigger_threshold: '', trigger_frequency: 'Daily',
    notify_sms: false, notify_email: false, notify_whatsapp: false,
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.rule_name.trim()) { toast.error('Rule name required'); return; }
    setSub(true);
    try {
      const r = await api.post('/school/hostel/alerts/rules', { ...form, trigger_after_days: form.trigger_after_days || null, trigger_threshold: form.trigger_threshold || null });
      if (r.data.success) { toast.success(r.data.message); setShowForm(false); onRefresh(); }
    } catch (err: any) { toast.error(err.response?.data?.message || 'Failed'); }
    finally { setSub(false); }
  };

  const handleToggle = async (id: number) => {
    setToggling(id);
    try { const r = await api.post(`/school/hostel/alerts/rules/${id}/toggle`); if (r.data.success) { toast.success(r.data.message); onRefresh(); } } catch { toast.error('Failed'); }
    finally { setToggling(null); }
  };

  const inp = 'w-full border border-slate-300 rounded-lg px-2 py-1 text-[10px] font-semibold outline-none focus:ring-1 focus:ring-indigo-500';
  const lbl = 'block text-[8px] font-bold text-slate-500 uppercase tracking-wide mb-0.5';

  return (
    <div className="space-y-2">
      <div className="flex justify-end">
        <button onClick={() => setShowForm(!showForm)}
          className="flex items-center gap-1 px-2 py-1 bg-indigo-600 text-white font-bold text-[9px] rounded-lg cursor-pointer hover:bg-indigo-700 transition">
          <Plus className="w-3 h-3" /> Add Rule
        </button>
      </div>

      {showForm && (
        <div className="bg-white border border-indigo-200 rounded-xl p-2.5 shadow-xs">
          <h3 className="text-[10px] font-bold text-slate-800 flex items-center gap-1.5 mb-2 pb-1 border-b border-slate-100">
            <Zap className="w-3 h-3 text-indigo-500" /> Create Auto-Alert Rule
          </h3>
          <form onSubmit={handleSubmit} className="space-y-1.5">
            <div className="grid grid-cols-2 gap-1.5">
              <div className="col-span-2">
                <label className={lbl}>Rule Name *</label>
                <input value={form.rule_name} onChange={e => setForm(f => ({ ...f, rule_name: e.target.value }))} className={inp} required />
              </div>
              <div>
                <label className={lbl}>Alert Type</label>
                <select value={form.alert_type} onChange={e => setForm(f => ({ ...f, alert_type: e.target.value }))} className={inp}>
                  {ALL_ALERT_TYPES.map(t => <option key={t}>{t}</option>)}
                </select>
              </div>
              <div>
                <label className={lbl}>Priority</label>
                <select value={form.priority} onChange={e => setForm(f => ({ ...f, priority: e.target.value }))} className={inp}>
                  {['Critical', 'High', 'Medium', 'Low'].map(p => <option key={p}>{p}</option>)}
                </select>
              </div>
              <div>
                <label className={lbl}>Target</label>
                <select value={form.target_type} onChange={e => setForm(f => ({ ...f, target_type: e.target.value }))} className={inp}>
                  {['Admin', 'Warden', 'Student', 'Parent', 'All'].map(t => <option key={t}>{t}</option>)}
                </select>
              </div>
              <div>
                <label className={lbl}>Frequency</label>
                <select value={form.trigger_frequency} onChange={e => setForm(f => ({ ...f, trigger_frequency: e.target.value }))} className={inp}>
                  {['Once', 'Daily', 'Weekly'].map(f => <option key={f}>{f}</option>)}
                </select>
              </div>
              <div>
                <label className={lbl}>Trigger After Days</label>
                <input type="number" min="0" value={form.trigger_after_days} onChange={e => setForm(f => ({ ...f, trigger_after_days: e.target.value }))} placeholder="e.g. 3 days" className={inp} />
              </div>
              <div>
                <label className={lbl}>Trigger Threshold</label>
                <input type="number" min="0" value={form.trigger_threshold} onChange={e => setForm(f => ({ ...f, trigger_threshold: e.target.value }))} placeholder="e.g. below 10 stock" className={inp} />
              </div>
              <div className="col-span-2">
                <label className={lbl}>Description</label>
                <input value={form.description} onChange={e => setForm(f => ({ ...f, description: e.target.value }))} className={inp} />
              </div>
              <div className="col-span-2 flex items-center gap-4">
                <p className="text-[8px] font-bold text-slate-500 uppercase">Channels:</p>
                {([{ key: 'notify_sms', label: 'SMS', Icon: Smartphone }, { key: 'notify_email', label: 'Email', Icon: Mail }, { key: 'notify_whatsapp', label: 'WhatsApp', Icon: MessageSquare }] as { key: string; label: string; Icon: React.ElementType }[]).map(ch => (
                  <label key={ch.key} className="flex items-center gap-1 cursor-pointer">
                    <input type="checkbox" checked={(form as any)[ch.key]} onChange={e => setForm(f => ({ ...f, [ch.key]: e.target.checked }))} className="w-3 h-3" />
                    <ch.Icon className="w-2.5 h-2.5 text-slate-500" />
                    <span className="text-[9px] font-bold text-slate-600">{ch.label}</span>
                  </label>
                ))}
              </div>
            </div>
            <div className="flex gap-1.5 pt-1">
              <button type="submit" disabled={submitting}
                className="flex-1 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-[10px] rounded-xl transition disabled:opacity-60 cursor-pointer">
                {submitting ? 'Saving...' : 'Save Rule'}
              </button>
              <button type="button" onClick={() => setShowForm(false)} className="px-3 border border-slate-300 text-slate-600 font-bold text-[10px] rounded-xl hover:bg-slate-50 transition cursor-pointer">Cancel</button>
            </div>
          </form>
        </div>
      )}

      {loading ? (
        <div className="text-center py-8 text-[10px] text-slate-400 font-semibold">Loading rules...</div>
      ) : (
        <div className="space-y-1">
          {rules.map(r => {
            const pc = priorityConfig[r.priority as keyof typeof priorityConfig] ?? priorityConfig.Low;
            const tc = alertTypeConfig[r.alert_type] ?? alertTypeConfig.Custom;
            const TypeIcon = tc.icon;
            return (
              <div key={r.id} className={`bg-white border rounded-xl p-2.5 shadow-xs transition ${!r.is_active ? 'opacity-50 border-slate-100' : 'border-slate-200 hover:border-indigo-200'}`}>
                <div className="flex items-start gap-2">
                  <div className={`p-1 rounded-lg flex-shrink-0 ${tc.bg}`}>
                    <TypeIcon className={`w-3 h-3 ${tc.color}`} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-1.5 flex-wrap">
                      <h4 className="text-[10px] font-bold text-slate-900 flex-1">{r.rule_name}</h4>
                      <PriorityBadge priority={r.priority} />
                    </div>
                    <div className="flex items-center gap-2 mt-0.5 flex-wrap text-[8px] text-slate-400 font-semibold">
                      <span>{r.alert_type}</span>
                      <span>→ {r.target_type}</span>
                      <span>{r.trigger_frequency}</span>
                      {r.trigger_after_days !== undefined && r.trigger_after_days !== null && <span>After {r.trigger_after_days}d</span>}
                      {r.trigger_threshold !== undefined && r.trigger_threshold !== null && <span>Below {r.trigger_threshold}</span>}
                      {r.last_triggered_at && <span className="text-indigo-400">Last: {r.last_triggered_at}</span>}
                    </div>
                    {r.description && <p className="text-[8px] text-slate-500 font-semibold mt-0.5">{r.description}</p>}
                    <div className="flex items-center gap-1 mt-0.5">
                      {r.notify_in_app  && <Bell className="w-2 h-2 text-indigo-400" />}
                      {r.notify_sms     && <Smartphone className="w-2 h-2 text-teal-400" />}
                      {r.notify_email   && <Mail className="w-2 h-2 text-amber-400" />}
                      {r.notify_whatsapp && <MessageSquare className="w-2 h-2 text-emerald-400" />}
                    </div>
                  </div>
                  <button onClick={() => handleToggle(r.id)} disabled={toggling === r.id}
                    className={`flex-shrink-0 flex items-center gap-1 px-2 py-1 rounded-lg border text-[8px] font-bold transition cursor-pointer ${r.is_active ? 'bg-emerald-50 border-emerald-200 text-emerald-700 hover:bg-emerald-100' : 'bg-slate-50 border-slate-200 text-slate-500 hover:bg-slate-100'}`}>
                    {r.is_active ? <ToggleRight className="w-3 h-3" /> : <ToggleLeft className="w-3 h-3" />}
                    {toggling === r.id ? '...' : r.is_active ? 'ON' : 'OFF'}
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};

// ─── SUBSCRIBERS TAB ──────────────────────────────────────────────────────────

interface SubscribersTabProps { subscribers: Subscriber[]; loading: boolean; onRefresh: () => void; }

const SubscribersTab: React.FC<SubscribersTabProps> = ({ subscribers, loading, onRefresh }) => {
  const [showForm, setSF]       = useState(false);
  const [submitting, setSub]    = useState(false);
  const [toggling, setToggling] = useState<number | null>(null);
  const [selected, setSelected] = useState<string[]>([]);

  const [form, setForm] = useState({
    name: '', type: 'Admin', phone: '', email: '', whatsapp: '',
    notify_sms: false, notify_email: false, notify_whatsapp: false,
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.name.trim()) { toast.error('Name required'); return; }
    setSub(true);
    try {
      const r = await api.post('/school/hostel/alerts/subscribers', { ...form, subscribed_types: selected });
      if (r.data.success) { toast.success(r.data.message); setSF(false); onRefresh(); }
    } catch (err: any) { toast.error(err.response?.data?.message || 'Failed'); }
    finally { setSub(false); }
  };

  const handleToggle = async (id: number) => {
    setToggling(id);
    try { const r = await api.post(`/school/hostel/alerts/subscribers/${id}/toggle`); if (r.data.success) { toast.success(r.data.message); onRefresh(); } } catch { toast.error('Failed'); }
    finally { setToggling(null); }
  };

  const typeColors: Record<string, string> = {
    Admin: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    Warden: 'bg-teal-50 text-teal-700 border-teal-200',
    Teacher: 'bg-violet-50 text-violet-700 border-violet-200',
    Parent: 'bg-amber-50 text-amber-700 border-amber-200',
    Other: 'bg-slate-50 text-slate-700 border-slate-200',
  };

  const inp = 'w-full border border-slate-300 rounded-lg px-2 py-1 text-[10px] font-semibold outline-none focus:ring-1 focus:ring-indigo-500';
  const lbl = 'block text-[8px] font-bold text-slate-500 uppercase tracking-wide mb-0.5';

  return (
    <div className="space-y-2">
      <div className="flex justify-end">
        <button onClick={() => setSF(!showForm)}
          className="flex items-center gap-1 px-2 py-1 bg-indigo-600 text-white font-bold text-[9px] rounded-lg cursor-pointer hover:bg-indigo-700 transition">
          <Plus className="w-3 h-3" /> Add Subscriber
        </button>
      </div>

      {showForm && (
        <div className="bg-white border border-indigo-200 rounded-xl p-2.5 shadow-xs">
          <h3 className="text-[10px] font-bold text-slate-800 flex items-center gap-1.5 mb-2 pb-1 border-b border-slate-100">
            <UserCheck className="w-3 h-3 text-indigo-500" /> Add Alert Subscriber
          </h3>
          <form onSubmit={handleSubmit} className="space-y-1.5">
            <div className="grid grid-cols-2 gap-1.5">
              <div>
                <label className={lbl}>Name *</label>
                <input value={form.name} onChange={e => setForm(f => ({ ...f, name: e.target.value }))} className={inp} required />
              </div>
              <div>
                <label className={lbl}>Type</label>
                <select value={form.type} onChange={e => setForm(f => ({ ...f, type: e.target.value }))} className={inp}>
                  {['Admin', 'Warden', 'Teacher', 'Parent', 'Other'].map(t => <option key={t}>{t}</option>)}
                </select>
              </div>
              <div>
                <label className={lbl}>Phone</label>
                <input value={form.phone} onChange={e => setForm(f => ({ ...f, phone: e.target.value }))} className={inp} />
              </div>
              <div>
                <label className={lbl}>Email</label>
                <input type="email" value={form.email} onChange={e => setForm(f => ({ ...f, email: e.target.value }))} className={inp} />
              </div>
              <div>
                <label className={lbl}>WhatsApp</label>
                <input value={form.whatsapp} onChange={e => setForm(f => ({ ...f, whatsapp: e.target.value }))} className={inp} />
              </div>
              <div className="flex items-end">
                <div className="flex items-center gap-3">
                  {[['notify_sms', 'SMS'], ['notify_email', 'Email'], ['notify_whatsapp', 'WhatsApp']].map(([k, l]) => (
                    <label key={k} className="flex items-center gap-1 cursor-pointer">
                      <input type="checkbox" checked={(form as any)[k]} onChange={e => setForm(f => ({ ...f, [k]: e.target.checked }))} className="w-3 h-3" />
                      <span className="text-[9px] font-bold text-slate-600">{l}</span>
                    </label>
                  ))}
                </div>
              </div>
              <div className="col-span-2">
                <label className={lbl}>Subscribe to Alert Types</label>
                <div className="flex flex-wrap gap-1 mt-0.5">
                  {ALL_ALERT_TYPES.map(t => (
                    <button key={t} type="button"
                      onClick={() => setSelected(prev => prev.includes(t) ? prev.filter(x => x !== t) : [...prev, t])}
                      className={`px-1.5 py-0.5 text-[8px] font-bold rounded border transition cursor-pointer ${selected.includes(t) ? 'bg-indigo-600 text-white border-indigo-600' : 'bg-white text-slate-500 border-slate-200 hover:bg-slate-50'}`}>
                      {t}
                    </button>
                  ))}
                </div>
              </div>
            </div>
            <div className="flex gap-1.5 pt-1">
              <button type="submit" disabled={submitting}
                className="flex-1 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-[10px] rounded-xl transition disabled:opacity-60 cursor-pointer">
                {submitting ? 'Adding...' : 'Add Subscriber'}
              </button>
              <button type="button" onClick={() => setSF(false)} className="px-3 border border-slate-300 text-slate-600 font-bold text-[10px] rounded-xl hover:bg-slate-50 transition cursor-pointer">Cancel</button>
            </div>
          </form>
        </div>
      )}

      {loading ? (
        <div className="text-center py-8 text-[10px] text-slate-400 font-semibold">Loading...</div>
      ) : (
        <div className="space-y-1">
          {subscribers.map(s => (
            <div key={s.id} className={`bg-white border rounded-xl p-2.5 shadow-xs transition ${!s.is_active ? 'opacity-50 border-slate-100' : 'border-slate-200 hover:border-indigo-200'}`}>
              <div className="flex items-start gap-2">
                <div className="w-8 h-8 rounded-full bg-indigo-50 border border-indigo-200 text-indigo-700 flex items-center justify-center text-[9px] font-black flex-shrink-0">
                  {s.name.split(' ').map(n => n[0]).join('').slice(0, 2)}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-1.5 flex-wrap">
                    <h4 className="text-[10px] font-bold text-slate-900">{s.name}</h4>
                    <span className={`text-[7px] font-bold border px-1 py-0.5 rounded ${typeColors[s.type] ?? typeColors.Other}`}>{s.type}</span>
                    {!s.is_active && <span className="text-[7px] font-bold bg-slate-100 text-slate-400 px-1 rounded">INACTIVE</span>}
                  </div>
                  <div className="flex items-center gap-3 mt-0.5 text-[8px] text-slate-500">
                    {s.phone && <span className="flex items-center gap-0.5"><Phone className="w-2 h-2" />{s.phone}</span>}
                    {s.email && <span className="flex items-center gap-0.5 truncate"><Mail className="w-2 h-2" />{s.email}</span>}
                  </div>
                  <div className="flex items-center gap-1 mt-0.5">
                    {s.notify_in_app  && <span title="In-App"><Bell className="w-2.5 h-2.5 text-indigo-400" /></span>}
                    {s.notify_sms     && <span title="SMS"><Smartphone className="w-2.5 h-2.5 text-teal-400" /></span>}
                    {s.notify_email   && <span title="Email"><Mail className="w-2.5 h-2.5 text-amber-400" /></span>}
                    {s.notify_whatsapp && <span title="WhatsApp"><MessageSquare className="w-2.5 h-2.5 text-emerald-400" /></span>}
                  </div>
                  {s.subscribed_types?.length > 0 && (
                    <div className="flex flex-wrap gap-0.5 mt-0.5">
                      {s.subscribed_types.slice(0, 5).map(t => (
                        <span key={t} className="text-[7px] font-bold bg-slate-100 text-slate-500 px-1 py-0.5 rounded">{t}</span>
                      ))}
                      {s.subscribed_types.length > 5 && <span className="text-[7px] font-bold text-slate-400">+{s.subscribed_types.length - 5}</span>}
                    </div>
                  )}
                </div>
                <button onClick={() => handleToggle(s.id)} disabled={toggling === s.id}
                  className={`flex-shrink-0 flex items-center gap-1 px-1.5 py-0.5 rounded-lg border text-[8px] font-bold transition cursor-pointer ${s.is_active ? 'bg-emerald-50 border-emerald-200 text-emerald-700' : 'bg-slate-50 border-slate-200 text-slate-500'}`}>
                  {s.is_active ? <ToggleRight className="w-3 h-3" /> : <ToggleLeft className="w-3 h-3" />}
                  {toggling === s.id ? '...' : s.is_active ? 'ON' : 'OFF'}
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

// ─── MAIN COMPONENT ───────────────────────────────────────────────────────────

const HostelAlertsManager: React.FC = () => {
  const [activeTab, setActiveTab] = useState<TabId>('dashboard');
  const [scanning, setScanning]   = useState(false);

  const [dashStats, setDashStats]       = useState<DashStats>({ total: 0, active: 0, critical: 0, unread: 0, resolved: 0, autoGenerated: 0, activeRules: 0, subscribers: 0 });
  const [byType, setByType]             = useState<Record<string, number>>({});
  const [byPriority, setByPriority]     = useState<Record<string, number>>({});
  const [byTarget, setByTarget]         = useState<Record<string, number>>({});
  const [channelStats, setChannelStats] = useState<any>({});
  const [criticalAlerts, setCritical]   = useState<Alert[]>([]);
  const [recentAlerts, setRecent]       = useState<Alert[]>([]);
  const [trend, setTrend]               = useState<any[]>([]);
  const [dashLoading, setDashLoad]      = useState(true);

  const [alerts, setAlerts]         = useState<Alert[]>([]);
  const [alertsLoading, setAL]      = useState(true);
  const [rules, setRules]           = useState<AlertRule[]>([]);
  const [rulesLoading, setRL]       = useState(true);
  const [subscribers, setSubscribers] = useState<Subscriber[]>([]);
  const [subsLoading, setSL]        = useState(true);

  const fetchDashboard = async () => {
    setDashLoad(true);
    try {
      const r = await api.get('/school/hostel/alerts/dashboard');
      if (r.data.success) {
        const d = r.data.data;
        setDashStats(d.stats); setByType(d.by_type); setByPriority(d.by_priority);
        setByTarget(d.by_target); setChannelStats(d.channel_stats);
        setCritical(d.critical_alerts); setRecent(d.recent_alerts); setTrend(d.trend);
      }
    } catch (e) { console.error(e); }
    finally { setDashLoad(false); }
  };

  const fetchAlerts      = async () => { setAL(true); try { const r = await api.get('/school/hostel/alerts/list'); if (r.data.success) setAlerts(r.data.data); } catch(e) { console.error(e); } finally { setAL(false); } };
  const fetchRules       = async () => { setRL(true); try { const r = await api.get('/school/hostel/alerts/rules'); if (r.data.success) setRules(r.data.data); } catch(e) { console.error(e); } finally { setRL(false); } };
  const fetchSubscribers = async () => { setSL(true); try { const r = await api.get('/school/hostel/alerts/subscribers'); if (r.data.success) setSubscribers(r.data.data); } catch(e) { console.error(e); } finally { setSL(false); } };

  useEffect(() => { fetchDashboard(); fetchAlerts(); fetchRules(); fetchSubscribers(); }, []);
  useEffect(() => {
    if (activeTab === 'dashboard')   { fetchDashboard(); fetchAlerts(); }
    if (activeTab === 'alerts')      fetchAlerts();
    if (activeTab === 'rules')       fetchRules();
    if (activeTab === 'subscribers') fetchSubscribers();
  }, [activeTab]);

  const handleMarkRead = async (id: number) => {
    try { const r = await api.post(`/school/hostel/alerts/${id}/read`); if (r.data.success) { toast.success('Marked as read'); fetchDashboard(); fetchAlerts(); } } catch { toast.error('Failed'); }
  };

  const handleResolve = async (id: number) => {
    try { const r = await api.post(`/school/hostel/alerts/${id}/resolve`, { resolved_by: 'Admin' }); if (r.data.success) { toast.success('Alert resolved!'); fetchDashboard(); fetchAlerts(); } } catch { toast.error('Failed'); }
  };

  const handleAutoScan = async () => {
    setScanning(true);
    try {
      const r = await api.post('/school/hostel/alerts/auto-scan');
      if (r.data.success) {
        toast.success(r.data.message, { duration: 4000 });
        fetchDashboard(); fetchAlerts();
      }
    } catch (err: any) { toast.error(err.response?.data?.message || 'Scan failed'); }
    finally { setScanning(false); }
  };

  const refreshAll = () => { fetchDashboard(); fetchAlerts(); fetchRules(); fetchSubscribers(); };

  const tabs: { id: TabId; label: string; icon: React.ElementType; badge?: number }[] = [
    { id: 'dashboard',   label: 'Dashboard',   icon: LayoutDashboard },
    { id: 'alerts',      label: 'Alerts',      icon: Bell,        badge: dashStats.active || undefined },
    { id: 'rules',       label: 'Rules',       icon: Settings,    badge: dashStats.activeRules || undefined },
    { id: 'subscribers', label: 'Subscribers', icon: Users,       badge: dashStats.subscribers || undefined },
  ];

  return (
    <div className="flex flex-col gap-1.5 p-1.5 md:p-2 text-[10px] font-sans antialiased text-slate-800 bg-slate-50 h-screen overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between bg-white border border-slate-200 shadow-xs rounded-xl px-2.5 py-1 gap-2 flex-shrink-0">
        <div className="flex items-center gap-1.5">
          <div className="p-1 bg-rose-50 text-rose-600 rounded-md">
            <BellRing className="w-3 h-3" />
          </div>
          <div>
            <h1 className="text-[11px] font-bold text-slate-900 leading-none">Smart Alerts &amp; Notifications</h1>
            <p className="text-[8px] font-semibold text-slate-400 mt-0.5 leading-none">
              {dashStats.active} active · {dashStats.critical > 0 ? `${dashStats.critical} critical · ` : ''}{dashStats.unread} unread · {dashStats.activeRules} rules
            </p>
          </div>
        </div>
        <div className="flex items-center gap-1">
          {dashStats.critical > 0 && (
            <span className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded-full text-[8px] font-bold bg-rose-600 text-white animate-pulse">
              <Flame className="w-2 h-2" /> {dashStats.critical} critical
            </span>
          )}
          {dashStats.unread > 0 && (
            <span className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded-full text-[8px] font-bold border bg-amber-50 text-amber-700 border-amber-200">
              <Bell className="w-2 h-2" /> {dashStats.unread} unread
            </span>
          )}
          <button onClick={handleAutoScan} disabled={scanning}
            className="flex items-center gap-0.5 px-1.5 py-0.5 bg-violet-600 hover:bg-violet-700 text-white font-bold text-[8px] rounded-lg cursor-pointer transition disabled:opacity-70">
            <ScanLine className={`w-2.5 h-2.5 ${scanning ? 'animate-spin' : ''}`} /> {scanning ? 'Scanning...' : 'Auto Scan'}
          </button>
          <button onClick={refreshAll} className="p-1 hover:bg-slate-100 rounded-lg transition cursor-pointer">
            <RefreshCw className="w-3 h-3 text-slate-400" />
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex flex-wrap gap-0.5 border-b border-slate-200 pb-0.5 flex-shrink-0">
        {tabs.map(tab => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button key={tab.id} onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-1 px-2 py-0.5 rounded-lg font-bold border transition duration-150 cursor-pointer text-[10px] shadow-xs ${
                isActive ? 'bg-indigo-600 text-white border-indigo-600' : 'bg-white text-slate-600 hover:text-slate-800 border-slate-200 hover:bg-slate-50'
              }`}>
              <Icon className={`w-2.5 h-2.5 ${isActive ? 'text-white' : 'text-slate-400'}`} />
              {tab.label}
              {tab.badge !== undefined && tab.badge > 0 && (
                <span className="ml-0.5 px-1 bg-rose-500 text-white text-[7px] font-black rounded-full leading-none py-0.5">{tab.badge}</span>
              )}
            </button>
          );
        })}
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto pr-0.5">
        {activeTab === 'dashboard' && (
          <DashboardTab stats={dashStats} byType={byType} byPriority={byPriority} byTarget={byTarget}
            channelStats={channelStats} criticalAlerts={criticalAlerts} recentAlerts={recentAlerts}
            trend={trend} loading={dashLoading} onTabChange={setActiveTab}
            onMarkRead={handleMarkRead} onResolve={handleResolve} />
        )}
        {activeTab === 'alerts' && (
          <AlertsTab alerts={alerts} loading={alertsLoading}
            onRefresh={() => { fetchAlerts(); fetchDashboard(); }}
            onRunScan={handleAutoScan} scanning={scanning} />
        )}
        {activeTab === 'rules' && (
          <RulesTab rules={rules} loading={rulesLoading} onRefresh={() => { fetchRules(); fetchDashboard(); }} />
        )}
        {activeTab === 'subscribers' && (
          <SubscribersTab subscribers={subscribers} loading={subsLoading} onRefresh={() => { fetchSubscribers(); fetchDashboard(); }} />
        )}
      </div>
    </div>
  );
};

export default HostelAlertsManager;
